server:
  port: 8080

spring:
  application:
    name: account-service

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

message: This is a default message.